# -*- coding: utf-8 -*-
"""MSc DS project final .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17d4VwnJ8sAt8PYCkX2zWE9_CX64k_Wan
"""

from google.colab import drive
drive.mount('/content/drive')

#Importing libraries

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Load SCAN-B cancer (9,206 samples) and normal (66 samples) gene expression datasets

cancer_data = pd.read_csv(
    "/content/drive/MyDrive/MSc Project code/SCANB.9206.genematrix_noNeg.txt",
    sep='\t',
    index_col=0,
    header=0,
    na_values='null'
)

# Load normal data
normal_data = pd.read_csv(
    "/content/drive/MyDrive/MSc Project code/Normal.66.genematrix_noNeg.txt",
    sep='\t',
    index_col=0,
    header=0
)

# Display dataset shapes and summary statistics

print("Cancer data shape:", cancer_data.shape)
print("Normal data shape:", normal_data.shape)

# Summary statistics
print("\nCancer data stats:")
display(cancer_data.describe())

print("\nNormal data stats:")
display(normal_data.describe())

# Rename CANCER samples
cancer_data.columns = [f"Cancer_{i}" for i in range(1, cancer_data.shape[1] + 1)]

# Rename NORMAL samples
normal_data.columns = [f"Normal_{i}" for i in range(1, normal_data.shape[1] + 1)]


print("Cancer samples :", cancer_data.columns[:5])
print("Normal samples :", normal_data.columns[:5])

cancer_data.head()

normal_data.head()

# Check values
  print("Max value in cancer_data:", cancer_data.max().max())
  print("Min value in cancer_data:", cancer_data.min().min())

# --- Data Preparation ---
# Split
temp_data = cancer_data.T
train_data, test_data = train_test_split(temp_data, train_size=8000, random_state=42)

train_data = train_data.T
test_data = test_data.T

# Precompute all possible normal indices
n_normal = normal_data.shape[1]
n_train = train_data.shape[1]
all_normal_indices = np.tile(np.arange(n_normal), int(np.ceil(n_train / n_normal)))[:n_train]

# Precompute log-transformed pure cancer targets (just for training)
y_train_pure = torch.FloatTensor(np.log2(train_data + 0.1).T.values)

# DAE Model
class DAE(nn.Module):
    def __init__(self, input_dim=19675):
        super(DAE, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 1024),
            nn.BatchNorm1d(1024),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.1),
            nn.Linear(1024, 512),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(0.1)
        )
        self.bottleneck = nn.Sequential(
            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.1)
        )
        self.decoder = nn.Sequential(
            nn.Linear(256, 512),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(0.1),
            nn.Linear(512, 1024),
            nn.BatchNorm1d(1024),
            nn.LeakyReLU(0.1),
            nn.Linear(1024, input_dim)
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.bottleneck(x)
        return self.decoder(x)

#Training the denoising autoencoder (DAE) to reconstruct clean cancer profiles from mixed inputs.

def train_model(X_train, y_train, X_val, y_val, batch_size=200, epochs=100):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Prepare training and validation data loaders
    train_dataset = TensorDataset(X_train, y_train)
    val_dataset = TensorDataset(X_val, y_val)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    # Define model, loss function and optimiser
    model = DAE().to(device)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.0005, weight_decay=1e-6)

    # Track best model and validation loss (for early stopping)
    best_val_loss = float('inf')
    best_model = None

    for epoch in range(epochs):
        # Training loop
        model.train()
        train_loss = 0
        for batch_x, batch_y in train_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_loader)

        # Validation
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for batch_x, batch_y in val_loader:
                batch_x, batch_y = batch_x.to(device), batch_y.to(device)
                outputs = model(batch_x)
                val_loss += criterion(outputs, batch_y).item()
        val_loss /= len(val_loader)

        # Early stopping check
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_model = model.state_dict()

        if epoch > 20 and val_loss > 1.5 * best_val_loss:
            break

    # Load best model
    model.load_state_dict(best_model)
    return model, train_loss, val_loss

# Validation function
def validate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            outputs = model(batch_x)
            total_loss += criterion(outputs, batch_y).item()
    return total_loss / len(loader)

# Evaluation function - Comparing noisy input vs. DAE output against clean targets
def evaluate(model, X_val, y_val):
    device = next(model.parameters()).device
    with torch.no_grad():       # Disable gradient calculation for evaluation
        Xv = X_val.to(device)
        yv = y_val.to(device)
        yhat = model(Xv)       # Generate reconstructed outputs from the model

        # Convert tensors to NumPy arrays for metric calculations
        yv_np = yv.cpu().numpy().reshape(-1)
        Xv_np = Xv.cpu().numpy().reshape(-1)
        yhat_np = yhat.cpu().numpy().reshape(-1)

        # Return reconstruction metrics (before vs. after DAE)
        return {
            'mse_noisy': mean_squared_error(yv_np, Xv_np),
            'r2_noisy': r2_score(yv_np, Xv_np),
            'mse_dae': mean_squared_error(yv_np, yhat_np),
            'r2_dae': r2_score(yv_np, yhat_np)
        }

# Creating folder to save trained models and results
import os
os.makedirs('saved_models', exist_ok=True)

results = []

# Define cancer-to-normal ratios to test
ratios_to_test = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]

for cancer_ratio in ratios_to_test:
    normal_ratio = 1.0 - cancer_ratio
    print(f"\n=== Testing {cancer_ratio:.0%} cancer / {normal_ratio:.0%} normal ===")

    # Create mixed data
    if cancer_ratio == 0:
        mixed_values = normal_data.iloc[:, all_normal_indices].values
    elif normal_ratio == 0:
        mixed_values = train_data.values
    else:
        mixed_values = (cancer_ratio * train_data.values +
                       normal_ratio * normal_data.iloc[:, all_normal_indices].values)

    # Applying Log transform
    mixed_train_log = torch.FloatTensor(np.log2(pd.DataFrame(
        mixed_values, index=train_data.index) + 0.1).T.values)

    # Split into training and validation sets
    X_train, X_val, y_train, y_val = train_test_split(
        mixed_train_log, y_train_pure, test_size=0.1, random_state=42)

    # Train and evaluate
    model, train_loss, val_loss = train_model(X_train, y_train, X_val, y_val)
    eval_results = evaluate(model, X_val, y_val)

    # Saving the model weights
    model_filename = f'saved_models/model_ratio_{cancer_ratio:.1f}.pth'
    torch.save(model.state_dict(), model_filename)
    print(f"Model saved: {model_filename}")

    # Saving the entire model
    full_model_filename = f'saved_models/full_model_ratio_{cancer_ratio:.1f}.pth'
    torch.save(model, full_model_filename)

    # Store results
    results.append({
        'cancer_ratio': cancer_ratio,
        'train_loss': train_loss,
        'val_loss': val_loss,
        'model_path': model_filename,  # Store path for later reference
        **eval_results,
        'mse_improvement': eval_results['mse_noisy'] - eval_results['mse_dae']
    })

    # Immediate output
    print(f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")
    print(f"MSE Improvement: {results[-1]['mse_improvement']:.4f}")

    # Saving all results for later analysis
results_df = pd.DataFrame(results)
results_df.to_csv('saved_models/training_results.csv', index=False)
print("\nAll models and results saved successfully!")

def plot_results(results):
    # Sort results by cancer_ratio in descending order (1.0 to 0.0)
    results_sorted = sorted(results, key=lambda x: x['cancer_ratio'], reverse=True)
    ratios = [r['cancer_ratio'] for r in results_sorted]

    plt.figure(figsize=(18, 12))

    # Plot 1: Training and validation loss
    plt.subplot(2, 2, 1)
    plt.plot(ratios, [r['train_loss'] for r in results_sorted], 'b-o', label='Train')
    plt.plot(ratios, [r['val_loss'] for r in results_sorted], 'r-o', label='Validation')
    plt.xlabel('Cancer Ratio'); plt.ylabel('Loss'); plt.title('Loss by Cancer Ratio')
    plt.legend(); plt.grid(True)
    plt.gca().invert_xaxis()  # Reverse x-axis

    # Plot 2: MSE (Baseline vs. DAE)
    plt.subplot(2, 2, 2)
    plt.plot(ratios, [r['mse_noisy'] for r in results_sorted], 'g-o', label='Baseline')
    plt.plot(ratios, [r['mse_dae'] for r in results_sorted], 'm-o', label='DAE')
    plt.xlabel('Cancer Ratio'); plt.ylabel('MSE'); plt.title('MSE Comparison')
    plt.legend(); plt.grid(True)
    plt.gca().invert_xaxis()

    # Plot 3: ΔMSE (Improvement by DAE)
    plt.subplot(2, 2, 3)
    plt.plot(ratios, [r['mse_improvement'] for r in results_sorted], 'c-o')
    plt.xlabel('Cancer Ratio'); plt.ylabel('ΔMSE'); plt.title('MSE Improvement')
    plt.grid(True)
    plt.gca().invert_xaxis()

    # Plot 4: R² Scores (Baseline vs. DAE)
    plt.subplot(2, 2, 4)
    plt.plot(ratios, [r['r2_noisy'] for r in results_sorted], 'y-o', label='Baseline')
    plt.plot(ratios, [r['r2_dae'] for r in results_sorted], 'k-o', label='DAE')
    plt.xlabel('Cancer Ratio'); plt.ylabel('R²'); plt.title('R² Scores')
    plt.legend(); plt.grid(True)
    plt.gca().invert_xaxis()

    plt.tight_layout()
    plt.show()

plot_results(results)

# Print final summary table of results (train/val loss, MSE, R², and ΔMSE for each cancer ratio)
print("\nFinal Results:")
print("Cancer\tTrain\tVal\tBaseline\tDAE\t\tImprovement")
print("Ratio\tLoss\tLoss\tMSE\tR²\tMSE\tR²\tΔMSE")
for r in results:
    print(f"{r['cancer_ratio']:.1f}\t{r['train_loss']:.4f}\t{r['val_loss']:.4f}\t"
          f"{r['mse_noisy']:.4f}\t{r['r2_noisy']:.4f}\t"
          f"{r['mse_dae']:.4f}\t{r['r2_dae']:.4f}\t"
          f"{r['mse_improvement']:.4f}")

# Prepare test data (pure cancer)
X_test = torch.FloatTensor(np.log2(test_data + 0.1).T.values)
y_test = torch.FloatTensor(np.log2(test_data + 0.1).T.values)  # Target is same as input for pure cancer

# Create test dataset and loader
test_dataset = TensorDataset(X_test, y_test)
test_loader = DataLoader(test_dataset, batch_size=200, shuffle=False)

# Function to evaluate on test data
def evaluate_test_corrected(model, test_loader, device):
    model.eval()
    criterion = nn.MSELoss()
    test_loss = 0
    all_outputs = []
    all_targets = []

    with torch.no_grad():
        for batch_x, batch_y in test_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            outputs = model(batch_x)
            test_loss += criterion(outputs, batch_y).item()

            # Store for metrics calculation
            all_outputs.append(outputs.cpu().numpy())
            all_targets.append(batch_y.cpu().numpy())

    test_loss /= len(test_loader)

    # Concatenate all batches
    all_outputs = np.concatenate(all_outputs, axis=0)
    all_targets = np.concatenate(all_targets, axis=0)

    # Calculate metrics - compare DAE output to target
    mse_dae = mean_squared_error(all_targets.reshape(-1), all_outputs.reshape(-1))
    r2_dae = r2_score(all_targets.reshape(-1), all_outputs.reshape(-1))

    return {
        'test_loss': test_loss,
        'mse_dae': mse_dae,
        'r2_dae': r2_dae
    }

# Evaluate each trained model on test data
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print("\n" + "="*60)
print("CORRECTED TEST DATA EVALUATION - Pure Cancer Samples")
print("="*60)
print("Trained on\tTest Loss\tDAE MSE\t\tDAE R²")
print("-"*55)

test_results = []
for cancer_ratio in ratios_to_test:
    try:
        # Load the model
        model = DAE().to(device)
        model_filename = f'saved_models/model_ratio_{cancer_ratio:.1f}.pth'
        model.load_state_dict(torch.load(model_filename))
        model.eval()

        # Evaluate on test data
        test_metrics = evaluate_test_corrected(model, test_loader, device)

        # Store results
        test_results.append({
            'trained_ratio': cancer_ratio,
            **test_metrics
        })

        print(f"{cancer_ratio:.1f}\t\t{test_metrics['test_loss']:.6f}\t{test_metrics['mse_dae']:.6f}\t{test_metrics['r2_dae']:.6f}")

    except FileNotFoundError:
        print(f"Model for ratio {cancer_ratio:.1f} not found, skipping...")
    except Exception as e:
        print(f"Error loading model for ratio {cancer_ratio:.1f}: {e}")

# Save test results
test_results_df = pd.DataFrame(test_results)
test_results_df.to_csv('saved_models/test_results_pure_cancer_corrected.csv', index=False)
print("\nTest results saved to 'saved_models/test_results_pure_cancer_corrected.csv'")

# Visualization of Results
def plot_pure_test_results(test_results):
    if not test_results:
        print("No test results to plot")
        return

    # Sort by trained ratio
    test_results_sorted = sorted(test_results, key=lambda x: x['trained_ratio'], reverse=True)
    ratios = [r['trained_ratio'] for r in test_results_sorted]

    plt.figure(figsize=(12, 5))

    # Plot 1: Test MSE
    plt.subplot(1, 2, 1)
    plt.plot(ratios, [r['mse_dae'] for r in test_results_sorted], 'b-o', linewidth=2, markersize=6)
    plt.xlabel('Training Cancer Ratio')
    plt.ylabel('Test MSE')
    plt.title('Reconstruction Error on Pure Cancer Test Data')
    plt.grid(True, alpha=0.3)
    plt.gca().invert_xaxis()

    # Plot 2: Test R²
    plt.subplot(1, 2, 2)
    plt.plot(ratios, [r['r2_dae'] for r in test_results_sorted], 'g-o', linewidth=2, markersize=6)
    plt.xlabel('Training Cancer Ratio')
    plt.ylabel('Test R²')
    plt.title('Reconstruction Quality on Pure Cancer Test Data')
    plt.grid(True, alpha=0.3)
    plt.gca().invert_xaxis()

    plt.tight_layout()
    plt.show()

# Plot the results
plot_pure_test_results(test_results)

# Analysis
if test_results:
    # Find best performing model
    best_model_mse = min(test_results, key=lambda x: x['mse_dae'])
    best_model_r2 = max(test_results, key=lambda x: x['r2_dae'])

    print(f"\nBest model by MSE: Trained on {best_model_mse['trained_ratio']:.1f} cancer ratio")
    print(f"MSE: {best_model_mse['mse_dae']:.6f}, R²: {best_model_mse['r2_dae']:.6f}")

    print(f"\nBest model by R²: Trained on {best_model_r2['trained_ratio']:.1f} cancer ratio")
    print(f"MSE: {best_model_r2['mse_dae']:.6f}, R²: {best_model_r2['r2_dae']:.6f}")

